### ISSUE TITLE
Not working under 3.30

### ISSUE THREAD

**Issue by AlonsoLP** [Thoma5/gnome-shell-extension-bottompanel#11]
This extension fails under GNOME 3.30.

squalou.jenkins@gmail.com commented in https://extensions.gnome.org/extension/949/bottompanel/:
for gnome 3.30 edit $HOME/.local/share/gnome-shell/extensions/bottompanel@tmoer93/extension.js line 20, replace global.screen.connect by : Main.layoutManager.connect line 31, replace global.screen.disconnect by global.display.disconnect enjoy !

When applying the changes proposed, extension loads but panel disappears.

**Comment by Thoma5** [comment]
I 'll take a look at it tomorrow.
