### ISSUE TITLE
Doesn't work with 3.38 (I can't live without BottomPanel)

### ISSUE THREAD

**Issue by MagnusPGBerg** [Thoma5/gnome-shell-extension-bottompanel#16]
BottomPanel doesn't work with Gnome 3.38
And I can't live without BottomPanel
It worked up to and with 3.36
Please, please make it work
Or give me a clue how I can fix it myself

**Comment by Thoma5** [comment]
Investigating this. They deprecated/removed the set_anchor_point function I was using. However i am still trying to figuring out how the pivot_point functions should be used... just replacing the set_anchor_point with set_pivot_point wasn't working.

**Comment by Thoma5** [comment]
Fixed it, will upload it for review to gnome extensions now

**Comment by MagnusPGBerg** [comment]
It works!!!
Thank you A thousand times. I am so grateful for your efforts. Thanks, thanks...
