### ISSUE TITLE
PanelBox.set_anchor_point is not a function error

### ISSUE THREAD

**Issue by arthur109** [Thoma5/gnome-shell-extension-bottompanel#17]
I am using Manjaro Gnome and am getting this error since having updated:
PanelBox.set_anchor_point is not a function

gnome 3.38.1

**Comment by Thoma5** [comment]
The gnome extension website is strange... i disabled the version that caused the problem and it, so the 3.38 incompatible old version was shown as update... whatever after almost a week, the new version is finally reviewed and downloadable. enjoy :)
