### ISSUE TITLE
Popup-menu class

### ISSUE THREAD

**Issue by zagortenay333** [Thoma5/gnome-shell-extension-bottompanel#7]
I don't understand why you added the `.popup-menu` class to the panel?
It causes issues in various themes.

Would be much better if you added a new class like `panel-bottom` or similiar.

**Comment by Thoma5** [comment]
Without it, there would be a large and ugly gap between the  popup menu bubble and the panel. Could you please describe the problem which occures for you and provide further information about the theme please. Maybe we can find a solution.

**Comment by zagortenay333** [comment]
In my Ciliora themes it looks crappy:
https://github.com/zagortenay333/ciliora-tertia-shell
https://github.com/zagortenay333/ciliora-secunda-shell

There has to be another way to fix this though. Sticking the `.panel-menu` class on the panel is just wrong.
Did you try using the `-boxpointer-gap` property with a negative value?

**Comment by Thoma5** [comment]
My extension does nothing else than move the native gnome panel to the bottom, so I 've to stick with the css themes of the shell. I tried a lot of things to fix the problem with the gaps, but the only thing that worked was to alter the .popup-menu.panel-menu class. I know it's not a proper way to fix it, but it works at least with the default theme and the arc and vertex theme. I see a small gap at the top and borders around the buttons with your theme too if I enable the bottom panel. I could fix the gap if I set down the panel height slightly, but the borders remain (see screenshot). I don't know why the borders even appear, as I only alter margin-top and nothing else. 
![bildschirmfoto vom 2016-08-15 21-14-32](https://cloud.githubusercontent.com/assets/6703063/17676170/8b636286-632d-11e6-851a-2f376604ca61.png)

**Comment by zagortenay333** [comment]
I added a bunch of panel-menu specific styling to produce cool effects and fix some bugs, and all those are leaking into the panel because of the `panel-menu` class.

So did you try the `-boxpointer-gap` property?

**Comment by Thoma5** [comment]
I've tried, it's working, but I still need the panel-menu class, and your theme would still be broken. But I've an idea. I will add an option to disable the css in my theme. But the you'll have to add the margin-top 0 or boxpointer with a negative value in your theme to make the extension work for your theme.

**Comment by zagortenay333** [comment]
Nah don't. If it can't be fixed cleanly than there's no point. I can always fix it some combinators, but it's gonna be some real ugly css. :smile: 

Closing this then.
