### ISSUE TITLE
bottom panel overlaps window and leaves the top panel place unoccupied

### ISSUE THREAD

**Issue by ctusch** [Thoma5/gnome-shell-extension-bottompanel#8]
Hi!

Your extension is the only one I could find that simply moves the top panel to the bottom of the screen. Unfortunately it doesn't seem to work quite right for me.

When I activate your extension the panel is correctly displayed at the bottom but the top area it previously occupied is not used by the windows. Instead there is a stripe where the wallpaper shines through.

Also the panel that is now at the bottom overlaps with my windows. So it seems like the panel is visually moved without the layout being aware of it.

I'm using Ubuntu GNOME 16.04 LTS (GNOME Shell v3.18.5). Any help is appreciated!

**Comment by Thoma5** [comment]
Hi,
have you already  tried restarting the GNOME Shell (Alt+F2 and type an r into the appearing command line)?
Kind regards

**Comment by ctusch** [comment]
Thank you, that solved the problem! :)
